name: tool_bag
description: Tool bag for all you needed

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  dcdg: ^3.0.0
  google_fonts: ^1.1.1
  intl: ^0.16.1
  path: ^1.7.0
  photo_manager: ^0.5.8
  shared_preferences: ^2.0.5
  sms: ^0.2.4
  sqflite: ^1.3.0
  webview_flutter: ^1.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - google_fonts/
